#!/bin/bash

# Tokyo Night Theme Preview Script
# Shows a preview of the Tokyo Night color scheme

echo "🌃 Tokyo Night Theme Preview"
echo "=============================="
echo ""

# Define Tokyo Night colors
declare -A colors=(
    ["bg"]="#1a1b26"
    ["fg"]="#c0caf5"
    ["blue"]="#7aa2f7"
    ["cyan"]="#7dcfff"
    ["green"]="#9ece6a"
    ["magenta"]="#bb9af7"
    ["orange"]="#ff9e64"
    ["purple"]="#9d7cd8"
    ["red"]="#f7768e"
    ["yellow"]="#e0af68"
    ["comment"]="#565f89"
    ["blue1"]="#2ac3de"
    ["green1"]="#73daca"
)

# Function to show color block
show_color() {
    local name="$1"
    local hex="$2"
    local rgb=$(printf "%d %d %d" 0x${hex:1:2} 0x${hex:3:2} 0x${hex:5:2})
    printf "  %-12s %s \033[48;2;${rgb}m    \033[0m %s\n" "$name" "$hex" "$hex"
}

echo "🎨 Primary Colors:"
show_color "Background" "${colors[bg]}"
show_color "Foreground" "${colors[fg]}"
show_color "Comment" "${colors[comment]}"
echo ""

echo "🌈 Accent Colors:"
show_color "Blue" "${colors[blue]}"
show_color "Cyan" "${colors[cyan]}"
show_color "Green" "${colors[green]}"
show_color "Magenta" "${colors[magenta]}"
show_color "Orange" "${colors[orange]}"
show_color "Purple" "${colors[purple]}"
show_color "Red" "${colors[red]}"
show_color "Yellow" "${colors[yellow]}"
echo ""

echo "💫 Additional Colors:"
show_color "Light Blue" "${colors[blue1]}"
show_color "Light Green" "${colors[green1]}"
echo ""

echo "📦 Components Themed:"
echo "  • Ghostty     - Terminal with Tokyo Night colors"
echo "  • BTOp        - System monitor with dark theme"
echo "  • Hyprland    - Window manager with Tokyo Night accents"
echo "  • Hyprlock    - Lock screen with dark theme"
echo "  • Mako        - Notifications with Tokyo Night styling"
echo "  • Neovim      - Editor with authentic Tokyo Night theme"
echo "  • Waybar      - Status bar with Tokyo Night colors"
echo "  • Fuzzel      - Application launcher with dark theme"
echo "  • Text Editor - Gnome Text Editor with Tokyo Night scheme"
echo ""

echo "🖼️  Backgrounds:"
echo "  • Generated by backgrounds.sh script"
echo "  • Dynamic wallpaper selection"
echo ""

echo "🚀 To activate this theme:"
echo "  theme-next"
echo ""
echo "✨ Tokyo Night brings a calm, dark aesthetic inspired by"
echo "   the neon lights of Tokyo at night. Perfect for coding"
echo "   sessions and focused work."
