# CypherRiot theme for Alacritty
# Based on your current color scheme with purple and blue accents

[colors.bright]
black = "0x686868"
blue = "0x7da6ff"     # accent5 from waybar
cyan = "0x0db9d7"     # accent2 from waybar  
green = "0x9ece6a"    # Green from your mic button
magenta = "0xbb9af7"  # accent4 from waybar
red = "0xff7a93"      # accent1 from waybar
white = "0xffffff"
yellow = "0xff9e64"   # accent3 from waybar

[colors.normal]
black = "0x222436"    # bgcolor from waybar
blue = "0x6a7de8"     # cpu_color from waybar
cyan = "0x0db9d7"     # accent2 from waybar
green = "0x7aa2f7"    # Matching your muted mic color
magenta = "0x9d7bd8"  # workspace_active from waybar
red = "0xff7a93"      # accent1 from waybar
white = "0xc7c7c7"
yellow = "0xe0af68"   # Softer yellow from CPU warnings

[colors.primary]
background = "0x1a1b26"  # Darker version of your waybar bgcolor
foreground = "0xffffff"  # fgcolor from waybar

# Additional theme colors for special cases
[colors.cursor]
text = "0x1a1b26"
cursor = "0x9d7bd8"  # workspace_active purple

[colors.selection]
text = "0xffffff"
background = "0x4a2b7a"  # window_color from waybar

[colors.search.matches]
foreground = "0x1a1b26"
background = "0xff9e64"  # accent3

[colors.search.focused_match]
foreground = "0x1a1b26" 
background = "0xbb9af7"  # accent4
